export const defaultUser = {
    firstName: "",
    lastName: "",
    username: "",
    email: "",
    phone: "",
    gender: "",
    image: "default-user-image.png",
    nationality: "",
    city: "",
    country: "",
    password: "",
    confirmPassword: "",
    fake: false,
    regDate: new Date(),
    twoFA: false,
    timezone: "Europe/Istanbul",
    currency: "USD",
    status: "active",
    walletBalance: 0.00,
};
