export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_COUNT = "FETCH_USERS_COUNT";
export const FETCH_USER = "FETCH_USER";
export const ADD_USER = "ADD_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";
export const CHANGE_USER_IMAGE = "CHANGE_USER_IMAGE";

export const FETCH_PLANS = "FETCH_PLANS";
export const ADD_PLAN = "ADD_PLAN";
export const EDIT_PLAN = "EDIT_PLAN";
export const DELETE_PLAN = "DELETE_PLAN";

export const FETCH_PAYMENT_METHODS = "FETCH_PAYMENT_METHODS";
export const ADD_PAYMENT_METHOD = "ADD_PAYMENT_METHOD";
export const EDIT_PAYMENT_METHOD = "EDIT_PAYMENT_METHOD";
export const DELETE_PAYMENT_METHOD = "DELETE_PAYMENT_METHOD";

export const FETCH_INVESTMENTS = "FETCH_INVESTMENTS";
export const FETCH_INVESTMENTS_COUNT = "FETCH_INVESTMENTS_COUNT";
export const FETCH_INVESTMENT = "FETCH_INVESTMENT";
export const NEW_INVESTMENT = "NEW_INVESTMENT";
export const CHANGE_INVESTMENT_STATUS = "CHANGE_INVESTMENT_STATUS";
export const DUPLICATE_INVESTMENT = "DUPLICATE_INVESTMENT";
export const DELETE_INVESTMENT = "DELETE_INVESTMENT";

export const FETCH_DEPOSITS = "FETCH_DEPOSITS";
export const FETCH_DEPOSITS_COUNT = "FETCH_DEPOSITS_COUNT";
export const NEW_DEPOSIT = "NEW_DEPOSIT";
export const CHANGE_DEPOSIT_STATUS = "CHANGE_DEPOSIT_STATUS";
export const DUPLICATE_DEPOSIT = "DUPLICATE_DEPOSIT";
export const DELETE_DEPOSIT = "DELETE_DEPOSIT";

export const FETCH_WITHDRAWALS = "FETCH_WITHDRAWALS";
export const FETCH_WITHDRAWALS_COUNT = "FETCH_WITHDRAWALS_COUNT";
export const NEW_WITHDRAWAL = "NEW_WITHDRAWAL";
export const CHANGE_WITHDRAWAL_STATUS = "CHANGE_WITHDRAWAL_STATUS";
export const DUPLICATE_WITHDRAWAL = "DUPLICATE_WITHDRAWAL";
export const DELETE_WITHDRAWAL = "DELETE_WITHDRAWAL";

export const FETCH_SUPPORT_TICKETS = "FETCH_SUPPORT_TICKETS";
export const FETCH_SUPPORT_TICKETS_COUNT = "FETCH_SUPPORT_TICKETS_COUNT";
export const NEW_SUPPORT_TICKET = "NEW_SUPPORT_TICKET";
export const CHANGE_SUPPORT_TICKET_STATUS = "CHANGE_SUPPORT_TICKET_STATUS";

export const FETCH_DOCUMENTS = "FETCH_DOCUMENTS";
export const FETCH_DOCUMENT = "FETCH_DOCUMENT";
export const CHANGE_KYC_STATUS = "CHANGE_KYC_STATUS";
export const NEW_KYC = "NEW_KYC";
export const EDIT_KYC = "EDIT_KYC";
export const DELETE_KYC = "DELETE_KYC";

export const FETCH_REFERRALS = "FETCH_REFERRALS";
export const FETCH_REFERRALS_COUNT = "FETCH_REFERRALS_COUNT";
export const FETCH_REFERRAL_BONUSES = "FETCH_REFERRAL_BONUSES";
export const FETCH_REFERRER = "FETCH_REFERRER";
